AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password')
User.create!(email: 'example@example.com', first_name: 'Peter', last_name: 'Test', password: 'password', password_confirmation: 'password')
Species.create!(name: 'Perro')
Species.create!(name: 'Gato')
Species.create!(name: 'Otros')
