AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password')
User.create!(email: 'example@example.com', first_name: 'Peter', last_name: 'Test', password: 'password', password_confirmation: 'password', phone: '095535795')
Species.create!(name: 'Perro', adoptable: true)
Species.create!(name: 'Gato', adoptable: true)
Species.create!(name: 'Caballo', adoptable: false)
Species.create!(name: 'Otros', adoptable: false)
