json.id @animal.id
json.chip_num @animal.chip_num
json.name @animal.name
json.sex @animal.sex
json.vaccines @animal.vaccines
json.castrated @animal.castrated
json.admission_date @animal.admission_date
json.birthdate @animal.birthdate
json.death_date @animal.death_date
json.sex @animal.sex
json.sex @animal.sex
json.species @animal.species.name
